INSERT INTO omc.address (city, country, street, zipcode) values ("Granada", "Spain", "Lorca", "21232");
INSERT INTO omc.address (city, country, street, zipcode) values ("Malaga", "Spain", "Canal", "23456");
INSERT INTO omc.address (city, country, street, zipcode) values ("Almeria", "Spain", "Victoria", "45362");
INSERT INTO omc.address (city, country, street, zipcode) values ("Barcelona", "Spain", "Llull", "08005");
INSERT INTO omc.address (city, country, street, zipcode) values ("Madrid", "Spain", "Francisco I", "32123");
INSERT INTO omc.users (name, username, password, address_id) values ("Luis", "luis23", "$2a$10$7Xh7F0wGyEQYgqz/CJNNu.V1JSfPqzx8SaZy.jNtjmnjVL7HFFJ5i", 1);
INSERT INTO omc.users (name, username, password, address_id) values ("Maria", "maria12", "$2a$10$7Xh7F0wGyEQYgqz/CJNNu.V1JSfPqzx8SaZy.jNtjmnjVL7HFFJ5i", 2);
INSERT INTO omc.users (name, username, password, address_id) values ("Lucas", "lucas22", "$2a$10$7Xh7F0wGyEQYgqz/CJNNu.V1JSfPqzx8SaZy.jNtjmnjVL7HFFJ5i", 3);
INSERT INTO omc.users (name, username, password, address_id) values ("Ana", "ana23", "$2a$10$7Xh7F0wGyEQYgqz/CJNNu.V1JSfPqzx8SaZy.jNtjmnjVL7HFFJ5i", 4);
INSERT INTO omc.users (name, username, password, address_id) values ("Juan", "juan55", "$2a$10$7Xh7F0wGyEQYgqz/CJNNu.V1JSfPqzx8SaZy.jNtjmnjVL7HFFJ5i", 5);
INSERT INTO omc.todos (title, completed, user_id) values ("a", FALSE, 1);
INSERT INTO omc.todos (title, completed, user_id) values ("b", TRUE, 1);
INSERT INTO omc.todos (title, completed, user_id) values ("c", FALSE, 3);
INSERT INTO omc.todos (title, completed, user_id) values ("d", FALSE, 1);
INSERT INTO omc.todos (title, completed, user_id) values ("s", TRUE, 1);
INSERT INTO omc.todos (title, completed, user_id) values ("e", FALSE, 3);
INSERT INTO omc.todos (title, completed, user_id) values ("q", FALSE, 1);
INSERT INTO omc.todos (title, completed, user_id) values ("w", TRUE, 4);
INSERT INTO omc.todos (title, completed, user_id) values ("t", FALSE, 3);
INSERT INTO omc.todos (title, completed, user_id) values ("y", FALSE, 2);
INSERT INTO omc.todos (title, completed, user_id) values ("u", TRUE, 5);
INSERT INTO omc.todos (title, completed, user_id) values ("j", FALSE, 3);
INSERT INTO omc.todos (title, completed, user_id) values ("g", TRUE, 4);
INSERT INTO omc.todos (title, completed, user_id) values ("l", FALSE, 3);
INSERT INTO omc.todos (title, completed, user_id) values ("m", FALSE, 2);
INSERT INTO omc.todos (title, completed, user_id) values ("ll", TRUE, 5);
INSERT INTO omc.todos (title, completed, user_id) values ("i", FALSE, 3);
INSERT INTO omc.todos (title, completed, user_id) values ("o", FALSE, 2);
INSERT INTO omc.todos (title, completed, user_id) values ("v", TRUE, 5);
INSERT INTO omc.todos (title, completed, user_id) values ("n", FALSE, 3);
INSERT INTO omc.todos (title, completed, user_id) values ("p", TRUE, 4);
INSERT INTO omc.todos (title, completed, user_id) values ("z", FALSE, 3);
INSERT INTO omc.todos (title, completed, user_id) values ("nn", FALSE, 2);
INSERT INTO omc.todos (title, completed, user_id) values ("vv", TRUE, 5);
INSERT INTO omc.todos (title, completed, user_id) values ("gg", FALSE, 3);

